# mysql server seeded with databases from dump files in the folder ./rpg_mysql
# The seeding only happens on the first start when the volume is created.
# If you need to reset the seeding, run "docker compose down -v" to delete the volume.
services:
  rpg_mysql:
    image: mysql:9.5.0
    container_name: rpg_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - rpg_mysql:/var/lib/mysql
      - ./rpg_mysql:/docker-entrypoint-initdb.d
    hostname: rpg_mysql

  rpg_neo4j:
    image: neo4j:5.26
    container_name: rpg_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/12345678"
    volumes:
      - rpg_neo4j:/data
    hostname: rpg_neo4j

  rpg_mongodb:
    image: mongo:7.0
    container_name: rpg_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      MONGO_INITDB_DATABASE: rpg_db
    volumes:
      - rpg_mongodb:/data/db
      - ./rpg_mongodb:/docker-entrypoint-initdb.d
    hostname: rpg_mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rpg_mysql:
    driver: local
  rpg_neo4j:
    driver: local
  rpg_mongodb:
    driver: local
