spring.application.name=choose-your-fate-backend
spring.config.import=optional:file:./.env[.properties],optional:file:./choose-your-fate-backend/.env[.properties]


spring.datasource.url=${MYSQL_URI:jdbc:mysql://localhost:3307/choose_your_fate}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:${MYSQL_ROOT_PASSWORD:123456}}

#tells Hibernate to not rewrite our schema
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

#jwt.secret=${JWT_SECRET}
jwt.secret=6ib1om/FI7YEYpSTlNfsgZZuMMxVCDwlTQfWU7bz9Os=

app.ai.enabled=${AI_ENABLED:true}
app.ai.strip-markdown=${AI_STRIP_MARKDOWN:true}
spring.ai.ollama.base-url=${AI_OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${AI_OLLAMA_CHAT_MODEL:glm-4.6:cloud}
spring.ai.ollama.chat.options.temperature=${AI_OLLAMA_TEMPERATURE:0.3}
