spring.application.name=choose-your-fate-backend
spring.config.import=optional:file:./.env[.properties],optional:file:./choose-your-fate-backend/.env[.properties]


spring.datasource.url=${MYSQL_URI:jdbc:mysql://localhost:3307/choose_your_fate}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:${MYSQL_ROOT_PASSWORD:123456}}

#tells Hibernate to not rewrite our schema
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#failover and failback
app.availability.primary-failure-threshold=${PRIMARY_FAILURE_THRESHOLD:2}
app.availability.replication.max-retries=${REPLICATION_MAX_RETRIES:3}
app.availability.failover.max-drain-jobs=${FAILOVER_MAX_DRAIN_JOBS:10}
app.availability.health-check-interval-ms=${HEALTH_CHECK_INTERVAL_MS:5000}
app.datasource.secondary.url=${MYSQL_SECONDARY_URI:jdbc:mysql://localhost:3308/choose_your_fate}
app.datasource.secondary.username=${MYSQL_SECONDARY_USERNAME:root}
app.datasource.secondary.password=${MYSQL_SECONDARY_PASSWORD:${MYSQL_SECONDARY_ROOT_PASSWORD:123456}}

server.port=8080

#jwt.secret=${JWT_SECRET}
jwt.secret=6ib1om/FI7YEYpSTlNfsgZZuMMxVCDwlTQfWU7bz9Os=

app.ai.enabled=${AI_ENABLED:true}
app.ai.strip-markdown=${AI_STRIP_MARKDOWN:true}
spring.ai.ollama.base-url=${AI_OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${AI_OLLAMA_CHAT_MODEL:glm-4.6:cloud}
spring.ai.ollama.chat.options.temperature=${AI_OLLAMA_TEMPERATURE:0.3}

elevenlabs.api.key=${ELEVEN_LABS_API_KEY:PlaceHolder}