name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./choose-your-fate-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: ./choose-your-fate-backend/target/*.jar
          retention-days: 1

  test:
    env:
      ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./choose-your-fate-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Unit and Integration Tests
        run: mvn clean verify